// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package yabai

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson22a65230DecodeGithubComRyantkingYabaictlYabai(in *jlexer.Lexer, out *Display) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "index":
			out.Index = int(in.Int())
		case "spaces":
			if in.IsNull() {
				in.Skip()
				out.Spaces = nil
			} else {
				in.Delim('[')
				if out.Spaces == nil {
					if !in.IsDelim(']') {
						out.Spaces = make([]int, 0, 8)
					} else {
						out.Spaces = []int{}
					}
				} else {
					out.Spaces = (out.Spaces)[:0]
				}
				for !in.IsDelim(']') {
					var v1 int
					v1 = int(in.Int())
					out.Spaces = append(out.Spaces, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson22a65230EncodeGithubComRyantkingYabaictlYabai(out *jwriter.Writer, in Display) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"index\":"
		out.RawString(prefix[1:])
		out.Int(int(in.Index))
	}
	{
		const prefix string = ",\"spaces\":"
		out.RawString(prefix)
		if in.Spaces == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Spaces {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.Int(int(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Display) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson22a65230EncodeGithubComRyantkingYabaictlYabai(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Display) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson22a65230EncodeGithubComRyantkingYabaictlYabai(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Display) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson22a65230DecodeGithubComRyantkingYabaictlYabai(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Display) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson22a65230DecodeGithubComRyantkingYabaictlYabai(l, v)
}
