{
  config,
  pkgs,
  ...
}: let
  inherit (config.workshop) configHome;
in {
  homebrew.casks = ["hammerspoon"];

  environment.systemPackages = with pkgs; [lua5_4 fennel];

  home.file = {
    ".hammerspoon/init.lua".text = ''      -- Generated by the Workshop -- DO NOT EDIT

      -- Set the config directory
      configdir = "${configHome}/hammerspoon"

      -- Nix-managed modules
      package.path = package.path .. ";${pkgs.fennel}/share/lua/5.4/?.lua"
      package.path = package.path .. ";${configHome}/hammerspoon/?.lua"

      -- Stackline setup
      package.path = package.path .. ";${configHome}/hammerspoon/?/init.lua"
      stackline_conf = require'stackline.conf'
      stackline_conf.paths.yabai = "${pkgs.yabai}/bin/yabai"

      -- Fennel setup
      fennel = require'fennel'
      fennel.path = fennel.path .. ";${configHome}/hammerspoon/?.fnl"
      fennel.path = fennel.path .. ";${configHome}/hammerspoon/?/init.fnl"
      fennel["macro-path"] = fennel["macro-path"] .. ";${configHome}/hammerspoon/?.fnl"
      fennel["macro-path"] = fennel["macro-path"] .. ";${configHome}/hammerspoon/?/init.fnl"
      debug.traceback = fennel.traceback
      table.insert(package.loaders or package.searchers, fennel.searcher)

      -- Load the config
      require 'core'
    '';

    ".hammerspoon/stackline".source = pkgs.sources.stackline.src;
  };
}
