(require-macros {: ki-} "zest.macros")

(ki- "<C-s>" [n] "write")
(ki- "<C-q>" [n] "wq")
(ki- "<C-x>" [n] "<cmd>BufferDelete<CR>")
(ki- "Y" [n] "y$")
(ki- "]b" "bp")
(ki- "[b" "bn")
(ki- "<A-[>" "vertical resize -5")
(ki- "<A-]>" "vertical resize +5")
