# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  alejandra = {
    pname = "alejandra";
    version = "91d4a0b00cde34758260c824fab0eabcc2f5c77c";
    src = fetchgit {
      url = "https://github.com/kamadorueda/alejandra.git";
      rev = "91d4a0b00cde34758260c824fab0eabcc2f5c77c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-7ZQWA/SJfgvSSoxPf2ukXLpcZ8Vj9XKdMtPhazb4p3c=";
    };
  };
  chemacs = {
    pname = "chemacs";
    version = "d722459287566e8c91ae077bf3d65966ebece190";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2.git";
      rev = "d722459287566e8c91ae077bf3d65966ebece190";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YD5GncKB2n0ybMNE1NHfjnIYe/Je3wdI0AgI2pcmxgQ=";
    };
  };
  fennel = {
    pname = "fennel";
    version = "06ab6224061d476249a7fdb0d7a0fc7e6299fa3d";
    src = fetchgit {
      url = "https://github.com/bakpakin/Fennel.git";
      rev = "06ab6224061d476249a7fdb0d7a0fc7e6299fa3d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-Ld6ew5abzCch5gMec8k+9Iw9zqtjOk/kx6hnzt5EZR0=";
    };
  };
  gofumpt = {
    pname = "gofumpt";
    version = "70d7433507d8d92bfa78a923e1f48de9b9e17203";
    src = fetchgit {
      url = "https://github.com/mvdan/gofumpt";
      rev = "70d7433507d8d92bfa78a923e1f48de9b9e17203";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-X+IdHmOpY2h9AooRh/Ly1DIn3oGhm6yxxekEBknLR3o=";
    };
  };
  goimapnotify = {
    pname = "goimapnotify";
    version = "8f1574b8cd2717f0620254a0213fa5a4fc840a5c";
    src = fetchgit {
      url = "https://gitlab.com/shackra/goimapnotify.git";
      rev = "8f1574b8cd2717f0620254a0213fa5a4fc840a5c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3tHe0msUWJ9G/o6D17muC0AZun3/E5Lqw7ba+9jODx0=";
    };
  };
  gotools = {
    pname = "gotools";
    version = "248c34b88a4148128f89e41923498bd86f805b7d";
    src = fetchgit {
      url = "https://go.googlesource.com/tools";
      rev = "248c34b88a4148128f89e41923498bd86f805b7d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-sX38wo9IR4unnkBsyC4TC4+Rhibhw8SC1x/2p2RL4uE=";
    };
  };
  nord-dircolors = {
    pname = "nord-dircolors";
    version = "35166d328992213194d7d02cd034e39da962f19e";
    src = fetchgit {
      url = "https://github.com/arcticicestudio/nord-dircolors.git";
      rev = "35166d328992213194d7d02cd034e39da962f19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6A3h1R1+kZbCwouUshvRpUL3fVkkDuHCD+bz8Jbq4M0=";
    };
  };
  stackline = {
    pname = "stackline";
    version = "b02ffe763b2cdf3a8b73255937bea49f071e6bbd";
    src = fetchgit {
      url = "https://github.com/AdamWagner/stackline.git";
      rev = "b02ffe763b2cdf3a8b73255937bea49f071e6bbd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oorQm+OpLOFh+aF4NDRimvnltS/bOlQYUZ1QqeeWlDY=";
    };
  };
  wlopm = {
    pname = "wlopm";
    version = "38af45c79771da1ef52309d101e881aaef94a823";
    src = fetchgit {
      url = "https://git.sr.ht/~leon_plickat/wlopm";
      rev = "38af45c79771da1ef52309d101e881aaef94a823";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-BVgq0Ht4Otid+McnwwmzdY7flqcBPe5br5879nyPgAE=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "983e0d720328b1b46b171a9b14f9b990cb034e0a";
    src = fetchgit {
      url = "https://github.com/koekeishiya/yabai";
      rev = "983e0d720328b1b46b171a9b14f9b990cb034e0a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-0bzdb0AlA7u1/pnG0vOk4iAQC7nFRmkExnfQGxK0ndY=";
    };
  };
}
