# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
}: {
  alejandra = {
    pname = "alejandra";
    version = "25cbef035e1ebf79fdf08f64ca6348ab4807b757";
    src = fetchgit {
      url = "https://github.com/kamadorueda/alejandra.git";
      rev = "25cbef035e1ebf79fdf08f64ca6348ab4807b757";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-imWi48JxT7l/1toc7NElP1/CBEbChTQ3n0gjBz6L7so=";
    };
  };
  chemacs = {
    pname = "chemacs";
    version = "d722459287566e8c91ae077bf3d65966ebece190";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2.git";
      rev = "d722459287566e8c91ae077bf3d65966ebece190";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YD5GncKB2n0ybMNE1NHfjnIYe/Je3wdI0AgI2pcmxgQ=";
    };
  };
  fennel = {
    pname = "fennel";
    version = "eb8e2d00c9846a9d78114966e0dfdb1c11981199";
    src = fetchgit {
      url = "https://github.com/bakpakin/Fennel.git";
      rev = "eb8e2d00c9846a9d78114966e0dfdb1c11981199";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-cE5cl/LGgdjEgzTp9+T+ogLeXeQ/ISbu1VtRU/Vs0sc=";
    };
  };
  gofumpt = {
    pname = "gofumpt";
    version = "8dda8068d9f339047fc1777b688afb66a0a0db17";
    src = fetchgit {
      url = "https://github.com/mvdan/gofumpt";
      rev = "8dda8068d9f339047fc1777b688afb66a0a0db17";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-XKgL8p1B9lCaCApCMqRc4dG3gqd74pfEq9OY1t9yCgI=";
    };
  };
  goimapnotify = {
    pname = "goimapnotify";
    version = "8f1574b8cd2717f0620254a0213fa5a4fc840a5c";
    src = fetchgit {
      url = "https://gitlab.com/shackra/goimapnotify.git";
      rev = "8f1574b8cd2717f0620254a0213fa5a4fc840a5c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3tHe0msUWJ9G/o6D17muC0AZun3/E5Lqw7ba+9jODx0=";
    };
  };
  gotools = {
    pname = "gotools";
    version = "ce6ce766265714553035d328a9be4f313c63e5fd";
    src = fetchgit {
      url = "https://go.googlesource.com/tools";
      rev = "ce6ce766265714553035d328a9be4f313c63e5fd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-0+0kfJmIs5O2NbNZFsH2txSEHSUnmqFHiKgaCMwq4yI=";
    };
  };
  nord-dircolors = {
    pname = "nord-dircolors";
    version = "35166d328992213194d7d02cd034e39da962f19e";
    src = fetchgit {
      url = "https://github.com/arcticicestudio/nord-dircolors.git";
      rev = "35166d328992213194d7d02cd034e39da962f19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6A3h1R1+kZbCwouUshvRpUL3fVkkDuHCD+bz8Jbq4M0=";
    };
  };
  wlopm = {
    pname = "wlopm";
    version = "24307414ca6881466f6e45d0ab8f196edde10a40";
    src = fetchgit {
      url = "https://git.sr.ht/~leon_plickat/wlopm";
      rev = "24307414ca6881466f6e45d0ab8f196edde10a40";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-kcUJVB5jP2qZ1YgJDEBsyn5AgwhRxQmzOrk0gKj1MeM=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v4.0.1";
    src = fetchFromGitHub {
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v4.0.1";
      fetchSubmodules = false;
      sha256 = "sha256-H1zMg+/VYaijuSDUpO6RAs/KLAAZNxhkfIC6CHk/xoI=";
    };
  };
}
