# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  chemacs = {
    pname = "chemacs";
    version = "d722459287566e8c91ae077bf3d65966ebece190";
    src = fetchgit {
      url = "https://github.com/plexus/chemacs2.git";
      rev = "d722459287566e8c91ae077bf3d65966ebece190";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-YD5GncKB2n0ybMNE1NHfjnIYe/Je3wdI0AgI2pcmxgQ=";
    };
    date = "2022-07-12";
  };
  fennel = {
    pname = "fennel";
    version = "e546e548e20d081e4157dee59537183fe41e51c8";
    src = fetchgit {
      url = "https://github.com/bakpakin/Fennel.git";
      rev = "e546e548e20d081e4157dee59537183fe41e51c8";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-eXtCv5Hlmo6qjxz008DwCNH2e/08Me0pmQELoHN1sRI=";
    };
    date = "2022-10-02";
  };
  goimapnotify = {
    pname = "goimapnotify";
    version = "8f1574b8cd2717f0620254a0213fa5a4fc840a5c";
    src = fetchgit {
      url = "https://gitlab.com/shackra/goimapnotify.git";
      rev = "8f1574b8cd2717f0620254a0213fa5a4fc840a5c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-3tHe0msUWJ9G/o6D17muC0AZun3/E5Lqw7ba+9jODx0=";
    };
    date = "2022-05-21";
  };
  nord-dircolors = {
    pname = "nord-dircolors";
    version = "35166d328992213194d7d02cd034e39da962f19e";
    src = fetchgit {
      url = "https://github.com/arcticicestudio/nord-dircolors.git";
      rev = "35166d328992213194d7d02cd034e39da962f19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6A3h1R1+kZbCwouUshvRpUL3fVkkDuHCD+bz8Jbq4M0=";
    };
    date = "2020-11-29";
  };
  stackline = {
    pname = "stackline";
    version = "b02ffe763b2cdf3a8b73255937bea49f071e6bbd";
    src = fetchgit {
      url = "https://github.com/AdamWagner/stackline.git";
      rev = "b02ffe763b2cdf3a8b73255937bea49f071e6bbd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-oorQm+OpLOFh+aF4NDRimvnltS/bOlQYUZ1QqeeWlDY=";
    };
    date = "2021-06-10";
  };
  yabai = {
    pname = "yabai";
    version = "351e7e304e7d1bbdd89b611c14dff5c116430996";
    src = fetchgit {
      url = "https://github.com/koekeishiya/yabai";
      rev = "351e7e304e7d1bbdd89b611c14dff5c116430996";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-5WtWLfiWVOqshbsx50fuEv8ab3U0y6z5+yvXoxpLokU=";
    };
    date = "2022-09-26";
  };
}
