# -*- mode: sh -*-
# shellcheck disable=SC1091,SC2059,SC2155

# $HOME/.bashrc: Bash interactive shell configuration

## Exit in non-interactive shells
case $- in
    *i*) ;;
      *) return;;
esac

## Kubernetes aliases
complete -o default -F __start_kubectl k

## History configuration
HISTSIZE=500000
HISTFILESIZE=100000
HISTTIMEFORMAT='%F %T '
HISTCONTROL=ignoreboth
export HISTIGNORE="&:[ ]*:exit:ls:bg:fg:history:clear"

## Incremental search
bind '"\e[A": history-search-backward'
bind '"\e[B": history-search-forward'
bind '"\e[C": forward-char'
bind '"\e[D": backward-char'

## Changing directories
CDPATH=".:~:~/Projects:~/Work:~/.local/src"
shopt -s autocd 2> /dev/null
shopt -s dirspell 2> /dev/null
shopt -s cdspell 2> /dev/null
shopt -s cdable_vars

## Shell options
set -o noclobber
set -o vi
shopt -s histappend
shopt -s checkwinsize
shopt -s globstar
shopt -s nocaseglob
bind Space:magic-space
bind "set completion-ignore-case on"
bind "set completion-map-case on"
bind "set show-all-if-ambiguous on"
bind "set mark-symlinked-directories on"

## Warning about root shells
if [ "$(id -u)" -eq 0 ]; then
    start="\033[1;37;41m"
    end="\033[0m"
    printf "\n"
    printf "  $start                                                                       $end\n"
    printf "  $start  WARNING: You are in a root shell. This is probably a very bad idea.  $end\n"
    printf "  $start                                                                       $end\n"
    printf "\n"
fi

## Load auxillary files
SHELL_CONFIG_HOME="$HOME/System/etc/shell"
[ -f "$HOME/System/usr/share/lscolors.sh" ] && source "$HOME/System/usr/share/lscolors.sh"
[ -f "$HOME/System/usr/share/lscolors.sh" ] && source "$HOME/System/usr/share/complete_alias"
[ -f "$HOME/System/usr/share/lscolors.sh" ] && source "$HOME/System/usr/share/kubectl_aliases"
[ -f "$SHELL_CONFIG_HOME/aliasrc" ] && source "$SHELL_CONFIG_HOME/aliasrc"
[ -f "$SHELL_CONFIG_HOME/profile" ] && source "$SHELL_CONFIG_HOME/profile"
[ -f "$SHELL_CONFIG_HOME/prompt" ] && source "$SHELL_CONFIG_HOME/prompt"

## Setup GPG with SSH support
export GPG_TTY="$(tty)"
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

## Enable completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Start the graphical server if not running
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx

### .bashrc ends here
