#!/usr/bin/env sh

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsslaunch slock &
autorandr --change
feh --bg-fill ~/Pictures/wallpapers/alena-aenami-wait.jpg

dbus-launch --sh-syntax --exit-with-session startdwm

# .xinitrc ends here
