#!/usr/bin/env sh

sudo yabai --load-sa

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:42:0 \
      window_border on \
      mouse_follows_focus off \
      focus_follows_mouse off \
      window_placement second_child \
      window_topmost off \
      window_shadow float \
      window_opacity on \
      window_opacity_duration 0.15 \
      active_window_opacity 1.0 \
      normal_window_opacity 0.95 \
      window_border_width 2 \
      window_border_radius 11 \
      window_animation_duration 0.15 \
      active_window_border_color 0xFF88C0D0 \
      normal_window_border_color 0x002E3440 \
      insert_feedback_color 0xFFA3BE8C \
      split_ratio 0.5 \
      auto_balance off \
      mouse_modifier fn \
      mouse_action1 move \
      mouse_action2 resize \
      mouse_drop_action swap \
      \
      top_padding 20 \
      bottom_badding 10 \
      left_padding 10 \
      right_padding 10 \
      window_gap 8

yabai -m rule --add app='Alfred Preferences' manage='off' sticky='on'
yabai -m rule --add app='^System Preferences$' manage='off' sticky='on' 
yabai -m rule --add app='Hammerspoon' layer='above' manage='on' sticky='on' title=''
yabai -m rule --add app='Hammerspoon Console' action="yabai -m window $(yabai -m query --windows | jq '.[] | select(.app==\"Hammerspoon\" and .name==\"Hammerspoon Console\") | .id') --minimize"

yabai -m config layout bsp

echo "yabai config loaded"

### yabairc ends here
