#!/usr/bin/env sh

source "$XDG_CONFIG_HOME/colorrc"

BG="0xFF$COLOR_BG"
BG_ALT="0xFF$COLOR_BG_ALT"
FG="0xFF$COLOR_FG"
FG_ALT="0xFF$COLOR_FG_ALT"
BLACK="0xFF$COLOR_BLACK"
RED="0xFF$COLOR_RED"
GREEN="0xFF$COLOR_GREEN"
YELLOW="0xFF$COLOR_YELLOW"
BLUE="0xFF$COLOR_BLUE"
MAGENTA="0xFF$COLOR_MAGENTA"
CYAN="0xFF$COLOR_CYAN"
WHITE="0xFF$COLOR_WHITE"

BAR_COLOR="0x99$COLOR_BG"
ACTIVE_SPACE_COLOR="0x44$COLOR_FG"
