# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  yabai = {
    pname = "yabai";
    version = "v4.0.0";
    src = fetchFromGitHub ({
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v4.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-rllgvj9JxyYar/DTtMn5QNeBTdGkfwqDr7WT3MvHBGI=";
    });
  };
}
