# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  chemacs = {
    pname = "chemacs";
    version = "868388321169eddf6dcb99f9b0d3ce734897b3de";
    src = fetchFromGitHub ({
      owner = "plexus";
      repo = "chemacs2";
      rev = "868388321169eddf6dcb99f9b0d3ce734897b3de";
      fetchSubmodules = false;
      sha256 = "sha256-XsJ2hHoQGoDbM7J+VvO1u0+f+jJCQqcUqQjzvTlnnG0=";
    });
  };
  gofumpt = {
    pname = "gofumpt";
    version = "b5619f8b06cad833eac1c454a48024599d8f5192";
    src = fetchFromGitHub ({
      owner = "mvdan";
      repo = "gofumpt";
      rev = "b5619f8b06cad833eac1c454a48024599d8f5192";
      fetchSubmodules = false;
      sha256 = "sha256-f4EIs/zUsyQnd5Qg2cxU6cbDKa9bbHTSV+9UG4gfPgM=";
    });
  };
  goimapnotify = {
    pname = "goimapnotify";
    version = "fdb48850f961909301b8e74fc9a9d27542e586bc";
    src = fetchgit {
      url = "https://gitlab.com/shackra/goimapnotify.git";
      rev = "fdb48850f961909301b8e74fc9a9d27542e586bc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6mYWeXcuuSdcvHcAh0Zd9nrYAQaPKZhxk7eYiYTZtRQ=";
    };
  };
  gotools = {
    pname = "gotools";
    version = "22b709631a034ac104cf20eb792086d9aa34b8ad";
    src = fetchgit {
      url = "https://go.googlesource.com/tools";
      rev = "22b709631a034ac104cf20eb792086d9aa34b8ad";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-i0JiQNFho9P3P1PiT94+FcPIkPnxFagIidDa0OXZvUc=";
    };
  };
  nord-dircolors = {
    pname = "nord-dircolors";
    version = "35166d328992213194d7d02cd034e39da962f19e";
    src = fetchFromGitHub ({
      owner = "arcticicestudio";
      repo = "nord-dircolors";
      rev = "35166d328992213194d7d02cd034e39da962f19e";
      fetchSubmodules = false;
      sha256 = "sha256-6A3h1R1+kZbCwouUshvRpUL3fVkkDuHCD+bz8Jbq4M0=";
    });
  };
  yabai = {
    pname = "yabai";
    version = "v4.0.0";
    src = fetchFromGitHub ({
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v4.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-rllgvj9JxyYar/DTtMn5QNeBTdGkfwqDr7WT3MvHBGI=";
    });
  };
}
