# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  chemacs = {
    pname = "chemacs";
    version = "d53aa5e5e298a4244b70ae59e9d9ba34752c4bbb";
    src = fetchFromGitHub ({
      owner = "plexus";
      repo = "chemacs2";
      rev = "d53aa5e5e298a4244b70ae59e9d9ba34752c4bbb";
      fetchSubmodules = false;
      sha256 = "sha256-qR5+TeAe3Kvnn5YSj4utvfhC8gzCXswP2ZP6vI0FOgM=";
    });
  };
  yabai = {
    pname = "yabai";
    version = "v4.0.0";
    src = fetchFromGitHub ({
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v4.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-rllgvj9JxyYar/DTtMn5QNeBTdGkfwqDr7WT3MvHBGI=";
    });
  };
}
