# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  chemacs = {
    pname = "chemacs";
    version = "d53aa5e5e298a4244b70ae59e9d9ba34752c4bbb";
    src = fetchFromGitHub ({
      owner = "plexus";
      repo = "chemacs2";
      rev = "d53aa5e5e298a4244b70ae59e9d9ba34752c4bbb";
      fetchSubmodules = false;
      sha256 = "sha256-qR5+TeAe3Kvnn5YSj4utvfhC8gzCXswP2ZP6vI0FOgM=";
    });
  };
  goimapnotify = {
    pname = "goimapnotify";
    version = "fdb48850f961909301b8e74fc9a9d27542e586bc";
    src = fetchgit {
      url = "https://gitlab.com/shackra/goimapnotify.git";
      rev = "fdb48850f961909301b8e74fc9a9d27542e586bc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6mYWeXcuuSdcvHcAh0Zd9nrYAQaPKZhxk7eYiYTZtRQ=";
    };
  };
  nord-dircolors = {
    pname = "nord-dircolors";
    version = "35166d328992213194d7d02cd034e39da962f19e";
    src = fetchgit {
      url = "https://github.com/arcticicestudio/nord-dircolors";
      rev = "35166d328992213194d7d02cd034e39da962f19e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-6A3h1R1+kZbCwouUshvRpUL3fVkkDuHCD+bz8Jbq4M0=";
    };
  };
  yabai = {
    pname = "yabai";
    version = "v4.0.0";
    src = fetchFromGitHub ({
      owner = "koekeishiya";
      repo = "yabai";
      rev = "v4.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-rllgvj9JxyYar/DTtMn5QNeBTdGkfwqDr7WT3MvHBGI=";
    });
  };
}
