# This file has been generated by node2nix 1.9.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? [ ] }:

let sources = { };
in {
  marked = nodeEnv.buildNodePackage {
    name = "marked";
    packageName = "marked";
    version = "4.0.4";
    src = fetchurl {
      url = "https://registry.npmjs.org/marked/-/marked-4.0.4.tgz";
      sha512 =
        "d8v7SensuOj+gxi0TGbqb2WtS60ycZfZuqtmAB9yz0JLotKerTob/47Qk9oLCDmn5G1dcdn3d5ydR+ih9dvS0A==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "A markdown parser built for speed";
      homepage = "https://marked.js.org";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
