# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  yabai = {
    pname = "yabai";
    version = "916d9133f9d13fb38678baa3d0adf3cfb9dff003";
    src = fetchFromGitHub ({
      owner = "koekeishiya";
      repo = "yabai";
      rev = "916d9133f9d13fb38678baa3d0adf3cfb9dff003";
      fetchSubmodules = false;
      sha256 = "sha256-RFEuVIMP9+HXnkSPRobCATzg9fsu48zoAFq7AqodLaQ=";
    });
  };
}
