# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  spacebar = {
    pname = "spacebar";
    version = "v1.4.0";
    src = fetchFromGitHub ({
      owner = "cmacrae";
      repo = "spacebar";
      rev = "v1.4.0";
      fetchSubmodules = false;
      sha256 = "sha256-4LiG43kPZtsm7SQ/28RaGMpYsDshCaGvc1mouPG3jFM=";
    });
  };
  yabai = {
    pname = "yabai";
    version = "916d9133f9d13fb38678baa3d0adf3cfb9dff003";
    src = fetchgit {
      url = "https://github.com/koekeishiya/yabai.git";
      rev = "916d9133f9d13fb38678baa3d0adf3cfb9dff003";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-RFEuVIMP9+HXnkSPRobCATzg9fsu48zoAFq7AqodLaQ=";
    };
  };
}
